name: GitHub Metrics

on:
  schedule:
    - cron: "0 * * * *" # runs every hour
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: bobbykafle
          template: classic
          base: header, activity, repositories
          plugin_languages: yes
          plugin_commits: yes
          output: github-metrics.svg

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github-metrics.svg
          git commit -m "Update GitHub metrics"
          git push
